export const COUNTRIES = [
  'Colombia',
  'México',
  'Argentina',
  'Chile',
  'Perú',
  'Ecuador',
  'Brasil',
  'Estados Unidos',
  'España',
  'Panamá',
  'Costa Rica',
  'República Dominicana',
  'Guatemala',
  'Honduras',
  'El Salvador',
  'Uruguay',
  'Paraguay',
  'Bolivia',
  'Venezuela',
  'Cuba',
  'Puerto Rico',
  'Nicaragua',
  'Canadá',
  'Reino Unido',
  'Alemania',
  'Francia',
  'Italia',
  'Portugal',
  'Países Bajos',
  'Suiza',
  'Australia',
  'Japón',
  'China',
  'Corea del Sur',
  'India',
  'Israel',
  'Emiratos Árabes Unidos',
  'Otro',
] as const

export type Country = typeof COUNTRIES[number]
